import Link from "next/link";
import "../globals.css";
import { getPages } from "@/sanity/sanity-utils";
import { GithubLogo, Linkedin, Twitter } from "../components/svgs";
import ContactMail from "../components/ContactMail";

export const metadata = {
  title: "My awesome site",
  description: "Generated by Next + Sanity",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = await getPages();

  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-10">
        <header className="flex items-center justify-between">
          <Link
            href="/"
            className="text-lg font-bold bg-gradient-to-r from-[#008F8C] via-[#0CABA8] to-[#0FC2C0] bg-clip-text text-transparent"
          >
            Home
          </Link>
          <div className="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between flex-grow">
            {pages.map((page) => (
              <Link
                key={page._id}
                href={`/${page.slug}`}
                className="hover:underline"
              >
                {page.title}
              </Link>
            ))}
            <ul className="flex flex-wrap items-center mt-3 text-sm font-medium text-gray-500 dark:text-gray-400 sm:mt-0">
              <li>
                <ContactMail />
              </li>
              <li className="px-2 text-lg pb-1">
                <Link
                  href={"https://www.linkedin.com/in/nejc-intihar-315482237/"}
                  target="_blank"
                >
                  <Linkedin />
                </Link>
              </li>

              <li className="px-2 text-lg">
                <Link href={"https://twitter.com/ninti21"} target="_blank">
                  <Twitter />
                </Link>
              </li>
              <li className="px-2 text-lg">
                <Link href={"https://github.com/nejcintihar"} target="_blank">
                  <GithubLogo />
                </Link>
              </li>
            </ul>
          </div>
        </header>
        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}
